### ISSUE TITLE
Problem: metamask signing error

### ISSUE THREAD

**Issue by leejw51crypto** [cronos-labs/play-cpp-sdk#29]
with localnet with chainid 777
```
Error: MiddlewareError(JsonRpcClientError(Eyre(failed to parse response

Caused by:
    invalid type: map, expected a string

Location:
game-sdk-extras/wallet-connect/src/client/socket.rs:135:42)))
```

**Comment by tomtau** [comment]
yeah, I think the error handling may be potentially improved -- right now, it expects `R` to be returned: https://github.com/crypto-com/game-sdk-extras/blob/main/wallet-connect/src/client/socket.rs#L134 but if the user rejects the request (or the wallet doesn't support it etc.), it'll be a different type... perhaps locally deserializing to the wrapped type (`ResponseData<R>`) https://github.com/crypto-com/game-sdk-extras/blob/main/wallet-connect/src/protocol/rpc.rs#L159 and returning the error message from `JsonRpcError` instead of having this `failed to parse response`

**Comment by tomtau** [comment]
The root cause is the same as for Trust Wallet -- see the comment: https://github.com/crypto-com/game-sdk-extras/blob/main/wallet-connect/examples/web3.rs#L21

**Comment by leejw51crypto** [comment]
catch error, and print out warning would be good
